/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import classes.RaceSimulator;
import javax.accessibility.AccessibleContext;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JTextField;

/**
 *
 * @author marti
 */
public class GUI extends javax.swing.JFrame {
    private RaceSimulator raceSim;
    private GUIHandler guiHandler;
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.raceSim = new RaceSimulator();
        this.guiHandler = new GUIHandler(this);
    }

    public void run() {
        this.raceSim.start();
        this.guiHandler.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TitleWindow = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BugattiWindow = new javax.swing.JPanel();
        winsBugatti = new javax.swing.JLabel();
        titleBugatti = new javax.swing.JLabel();
        winsTitleBugatti = new javax.swing.JLabel();
        QueueBugatti1 = new javax.swing.JTextField();
        QueueTitleBugatti1 = new javax.swing.JLabel();
        QueueBugatti2 = new javax.swing.JTextField();
        QueueTitleBugatti2 = new javax.swing.JLabel();
        QueueBugatti3 = new javax.swing.JTextField();
        QueueTitleBugatti3 = new javax.swing.JLabel();
        QueueBugatti4 = new javax.swing.JTextField();
        QueueTitleBugatti4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AIWindow = new javax.swing.JPanel();
        AITime = new javax.swing.JLabel();
        StopButton = new javax.swing.JButton();
        AITimeIncrease = new javax.swing.JButton();
        AITimeDecrease = new javax.swing.JButton();
        qtyRounds = new javax.swing.JLabel();
        roundsTitle = new javax.swing.JLabel();
        AIStatus = new javax.swing.JLabel();
        AITimeTitle = new javax.swing.JLabel();
        AITitle = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ResultWindowBugatti = new javax.swing.JPanel();
        RacingTitleBugatti = new javax.swing.JLabel();
        RacingTimeTitleBugatti = new javax.swing.JLabel();
        RacingTimeBugatti = new javax.swing.JLabel();
        RacingIDTitleBugatti = new javax.swing.JLabel();
        RacingIDBugatti = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ResultWindow = new javax.swing.JPanel();
        ResultTitle = new javax.swing.JLabel();
        Result = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ResultWindowLamborghini = new javax.swing.JPanel();
        RacingTitleLamborghini = new javax.swing.JLabel();
        RacingTimeTitleLamborghini = new javax.swing.JLabel();
        RacingIDTitleLamborghini = new javax.swing.JLabel();
        RacingIDLamborghini = new javax.swing.JLabel();
        RacingTimeLamborghini = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LamborghiniWindow = new javax.swing.JPanel();
        winsLamborghini = new javax.swing.JLabel();
        titleLamborghini = new javax.swing.JLabel();
        winsTitleLamborghini = new javax.swing.JLabel();
        QueueLamborghini1 = new javax.swing.JTextField();
        QueueTitleLamborghini1 = new javax.swing.JLabel();
        QueueLamborghini2 = new javax.swing.JTextField();
        QueueTitleLamborghini2 = new javax.swing.JLabel();
        QueueLamborghini3 = new javax.swing.JTextField();
        QueueTitleLamborghini3 = new javax.swing.JLabel();
        QueueLamborghini4 = new javax.swing.JTextField();
        QueueTitleLamborghini4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleWindow.setBackground(new java.awt.Color(51, 51, 51));
        TitleWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Proyecto 2 SO - Samer Ghattas y Martin Rojas ");
        TitleWindow.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 5, 1120, 30));

        jPanel1.add(TitleWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 40));

        BugattiWindow.setBackground(new java.awt.Color(255, 153, 102));
        BugattiWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        winsBugatti.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        winsBugatti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winsBugatti.setText("10");
        winsBugatti.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BugattiWindow.add(winsBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 310, 110));

        titleBugatti.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleBugatti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleBugatti.setText("Bugatti");
        titleBugatti.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        BugattiWindow.add(titleBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 310, 50));

        winsTitleBugatti.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        winsTitleBugatti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winsTitleBugatti.setText("Carreras ganadas");
        BugattiWindow.add(winsTitleBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 330, -1));

        QueueBugatti1.setEditable(false);
        QueueBugatti1.setBackground(new java.awt.Color(204, 204, 255));
        BugattiWindow.add(QueueBugatti1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 390, 30));

        QueueTitleBugatti1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QueueTitleBugatti1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        QueueTitleBugatti1.setText("Cola número 1");
        BugattiWindow.add(QueueTitleBugatti1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 350, -1));

        QueueBugatti2.setEditable(false);
        QueueBugatti2.setBackground(new java.awt.Color(204, 204, 255));
        QueueBugatti2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueueBugatti2ActionPerformed(evt);
            }
        });
        BugattiWindow.add(QueueBugatti2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 390, 30));

        QueueTitleBugatti2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QueueTitleBugatti2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        QueueTitleBugatti2.setText("Cola número 2");
        BugattiWindow.add(QueueTitleBugatti2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 350, -1));

        QueueBugatti3.setEditable(false);
        QueueBugatti3.setBackground(new java.awt.Color(204, 204, 255));
        BugattiWindow.add(QueueBugatti3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 390, 30));

        QueueTitleBugatti3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QueueTitleBugatti3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        QueueTitleBugatti3.setText("Cola número 3");
        BugattiWindow.add(QueueTitleBugatti3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 350, -1));

        QueueBugatti4.setEditable(false);
        QueueBugatti4.setBackground(new java.awt.Color(204, 204, 255));
        BugattiWindow.add(QueueBugatti4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 390, 30));

        QueueTitleBugatti4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QueueTitleBugatti4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        QueueTitleBugatti4.setText("Cola de refuerzo");
        BugattiWindow.add(QueueTitleBugatti4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 350, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bugattiBackground.png"))); // NOI18N
        BugattiWindow.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 550));

        jPanel1.add(BugattiWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 430, 550));

        AIWindow.setBackground(new java.awt.Color(255, 255, 255));
        AIWindow.setPreferredSize(new java.awt.Dimension(310, 138));
        AIWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AITime.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        AITime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AITime.setText("10");
        AIWindow.add(AITime, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 60, 30));

        StopButton.setText("Parar");
        StopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopButtonActionPerformed(evt);
            }
        });
        AIWindow.add(StopButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 70, 30));

        AITimeIncrease.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AITimeIncrease.setText("+");
        AITimeIncrease.setAlignmentY(0.0F);
        AITimeIncrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AITimeIncreaseActionPerformed(evt);
            }
        });
        AIWindow.add(AITimeIncrease, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 50, 30));

        AITimeDecrease.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AITimeDecrease.setText("-");
        AITimeDecrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AITimeDecreaseActionPerformed(evt);
            }
        });
        AIWindow.add(AITimeDecrease, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 50, 30));

        qtyRounds.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        qtyRounds.setText("0");
        AIWindow.add(qtyRounds, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 60, -1));

        roundsTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        roundsTitle.setText("RONDAS:");
        AIWindow.add(roundsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        AIStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AIStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AIStatus.setText("Esperando");
        AIWindow.add(AIStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 290, 30));

        AITimeTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AITimeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AITimeTitle.setText("Tiempo de sim.");
        AIWindow.add(AITimeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 270, 20));

        AITitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AITitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AITitle.setText("Inteligencia Artificial");
        AIWindow.add(AITitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 290, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/AIBackground.png"))); // NOI18N
        AIWindow.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 320, 210));

        jPanel1.add(AIWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 310, 210));

        ResultWindowBugatti.setBackground(new java.awt.Color(255, 204, 153));
        ResultWindowBugatti.setPreferredSize(new java.awt.Dimension(310, 138));
        ResultWindowBugatti.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RacingTitleBugatti.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RacingTitleBugatti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RacingTitleBugatti.setText("Bugatti corriendo");
        ResultWindowBugatti.add(RacingTitleBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 290, 40));

        RacingTimeTitleBugatti.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RacingTimeTitleBugatti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RacingTimeTitleBugatti.setText("Tiempo:");
        ResultWindowBugatti.add(RacingTimeTitleBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 70, 30));

        RacingTimeBugatti.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        RacingTimeBugatti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RacingTimeBugatti.setText("N/A");
        ResultWindowBugatti.add(RacingTimeBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 70, 30));

        RacingIDTitleBugatti.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RacingIDTitleBugatti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RacingIDTitleBugatti.setText("ID:");
        ResultWindowBugatti.add(RacingIDTitleBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 40, 30));

        RacingIDBugatti.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        RacingIDBugatti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RacingIDBugatti.setText("B8");
        ResultWindowBugatti.add(RacingIDBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 40, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/orangeBackground.jpg"))); // NOI18N
        ResultWindowBugatti.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 110));

        jPanel1.add(ResultWindowBugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, 110));

        ResultWindow.setBackground(new java.awt.Color(153, 153, 255));
        ResultWindow.setPreferredSize(new java.awt.Dimension(310, 138));
        ResultWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ResultTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ResultTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultTitle.setText("RESULTADOS");
        ResultWindow.add(ResultTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 290, 40));

        Result.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Result.setText("Lamborghini ganó");
        ResultWindow.add(Result, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 290, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("(Última Carrera)");
        ResultWindow.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 230, -1));
        ResultWindow.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 120));

        jPanel1.add(ResultWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, 120));

        ResultWindowLamborghini.setBackground(new java.awt.Color(204, 204, 204));
        ResultWindowLamborghini.setPreferredSize(new java.awt.Dimension(310, 138));
        ResultWindowLamborghini.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RacingTitleLamborghini.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RacingTitleLamborghini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RacingTitleLamborghini.setText("Lamborghini corriendo");
        ResultWindowLamborghini.add(RacingTitleLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 290, 40));

        RacingTimeTitleLamborghini.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RacingTimeTitleLamborghini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RacingTimeTitleLamborghini.setText("Tiempo:");
        ResultWindowLamborghini.add(RacingTimeTitleLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 70, 30));

        RacingIDTitleLamborghini.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RacingIDTitleLamborghini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RacingIDTitleLamborghini.setText("ID:");
        ResultWindowLamborghini.add(RacingIDTitleLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 40, 30));

        RacingIDLamborghini.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        RacingIDLamborghini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RacingIDLamborghini.setText("B8");
        ResultWindowLamborghini.add(RacingIDLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 40, 30));

        RacingTimeLamborghini.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        RacingTimeLamborghini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RacingTimeLamborghini.setText("N/A");
        ResultWindowLamborghini.add(RacingTimeLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 70, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/grayBackground.png"))); // NOI18N
        ResultWindowLamborghini.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 110));

        jPanel1.add(ResultWindowLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, -1, 110));

        LamborghiniWindow.setBackground(new java.awt.Color(153, 153, 153));
        LamborghiniWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        winsLamborghini.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        winsLamborghini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winsLamborghini.setText("10");
        winsLamborghini.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LamborghiniWindow.add(winsLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 310, 110));

        titleLamborghini.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleLamborghini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLamborghini.setText("Lamborghini");
        titleLamborghini.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        LamborghiniWindow.add(titleLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 310, 50));

        winsTitleLamborghini.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        winsTitleLamborghini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winsTitleLamborghini.setText("Carreras ganadas");
        LamborghiniWindow.add(winsTitleLamborghini, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 330, -1));

        QueueLamborghini1.setEditable(false);
        QueueLamborghini1.setBackground(new java.awt.Color(204, 204, 255));
        LamborghiniWindow.add(QueueLamborghini1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 390, 30));

        QueueTitleLamborghini1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QueueTitleLamborghini1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        QueueTitleLamborghini1.setText("Cola número 1");
        LamborghiniWindow.add(QueueTitleLamborghini1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 350, -1));

        QueueLamborghini2.setEditable(false);
        QueueLamborghini2.setBackground(new java.awt.Color(204, 204, 255));
        LamborghiniWindow.add(QueueLamborghini2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 390, 30));

        QueueTitleLamborghini2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QueueTitleLamborghini2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        QueueTitleLamborghini2.setText("Cola número 2");
        LamborghiniWindow.add(QueueTitleLamborghini2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 350, -1));

        QueueLamborghini3.setEditable(false);
        QueueLamborghini3.setBackground(new java.awt.Color(204, 204, 255));
        LamborghiniWindow.add(QueueLamborghini3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 390, 30));

        QueueTitleLamborghini3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QueueTitleLamborghini3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        QueueTitleLamborghini3.setText("Cola número 3");
        LamborghiniWindow.add(QueueTitleLamborghini3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 350, -1));

        QueueLamborghini4.setEditable(false);
        QueueLamborghini4.setBackground(new java.awt.Color(204, 204, 255));
        LamborghiniWindow.add(QueueLamborghini4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 390, 30));

        QueueTitleLamborghini4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        QueueTitleLamborghini4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        QueueTitleLamborghini4.setText("Cola de refuerzo");
        LamborghiniWindow.add(QueueTitleLamborghini4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 350, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/lamborghiniBackground.png"))); // NOI18N
        LamborghiniWindow.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 550));

        jPanel1.add(LamborghiniWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 430, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public GUIHandler getGuiHandler() {
        return guiHandler;
    }

    public void setGuiHandler(GUIHandler guiHandler) {
        this.guiHandler = guiHandler;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getRoundsTitle() {
        return roundsTitle;
    }

    public void setRoundsTitle(JLabel roundsTitle) {
        this.roundsTitle = roundsTitle;
    }

    public RaceSimulator getRaceSim() {
        return raceSim;
    }

    public void setRaceSim(RaceSimulator raceSim) {
        this.raceSim = raceSim;
    }
    
    public JLabel getAIStatus() {
        return AIStatus;
    }

    public void setAIStatus(JLabel AIStatus) {
        this.AIStatus = AIStatus;
    }

    public JLabel getAITime() {
        return AITime;
    }

    public void setAITime(JLabel AITime) {
        this.AITime = AITime;
    }

    public JButton getAITimeDecrease() {
        return AITimeDecrease;
    }

    public void setAITimeDecrease(JButton AITimeDecrease) {
        this.AITimeDecrease = AITimeDecrease;
    }

    public JButton getAITimeIncrease() {
        return AITimeIncrease;
    }

    public void setAITimeIncrease(JButton AITimeIncrease) {
        this.AITimeIncrease = AITimeIncrease;
    }

    public JLabel getAITimeTitle() {
        return AITimeTitle;
    }

    public void setAITimeTitle(JLabel AITimeTitle) {
        this.AITimeTitle = AITimeTitle;
    }

    public JLabel getAITitle() {
        return AITitle;
    }

    public void setAITitle(JLabel AITitle) {
        this.AITitle = AITitle;
    }

    public JPanel getAIWindow() {
        return AIWindow;
    }

    public void setAIWindow(JPanel AIWindow) {
        this.AIWindow = AIWindow;
    }

    public JPanel getBugattiWindow() {
        return BugattiWindow;
    }

    public void setBugattiWindow(JPanel BugattiWindow) {
        this.BugattiWindow = BugattiWindow;
    }

    public JPanel getLamborghiniWindow() {
        return LamborghiniWindow;
    }

    public void setLamborghiniWindow(JPanel LamborghiniWindow) {
        this.LamborghiniWindow = LamborghiniWindow;
    }

    public JTextField getQueueBugatti1() {
        return QueueBugatti1;
    }

    public void setQueueBugatti1(JTextField QueueBugatti1) {
        this.QueueBugatti1 = QueueBugatti1;
    }

    public JTextField getQueueBugatti2() {
        return QueueBugatti2;
    }

    public void setQueueBugatti2(JTextField QueueBugatti2) {
        this.QueueBugatti2 = QueueBugatti2;
    }

    public JTextField getQueueBugatti3() {
        return QueueBugatti3;
    }

    public void setQueueBugatti3(JTextField QueueBugatti3) {
        this.QueueBugatti3 = QueueBugatti3;
    }

    public JTextField getQueueBugatti4() {
        return QueueBugatti4;
    }

    public void setQueueBugatti4(JTextField QueueBugatti4) {
        this.QueueBugatti4 = QueueBugatti4;
    }

    public JTextField getQueueLamborghini1() {
        return QueueLamborghini1;
    }

    public void setQueueLamborghini1(JTextField QueueLamborghini1) {
        this.QueueLamborghini1 = QueueLamborghini1;
    }

    public JTextField getQueueLamborghini2() {
        return QueueLamborghini2;
    }

    public void setQueueLamborghini2(JTextField QueueLamborghini2) {
        this.QueueLamborghini2 = QueueLamborghini2;
    }

    public JTextField getQueueLamborghini3() {
        return QueueLamborghini3;
    }

    public void setQueueLamborghini3(JTextField QueueLamborghini3) {
        this.QueueLamborghini3 = QueueLamborghini3;
    }

    public JTextField getQueueLamborghini4() {
        return QueueLamborghini4;
    }

    public void setQueueLamborghini4(JTextField QueueLamborghini4) {
        this.QueueLamborghini4 = QueueLamborghini4;
    }

    public JLabel getQueueTitleBugatti1() {
        return QueueTitleBugatti1;
    }

    public void setQueueTitleBugatti1(JLabel QueueTitleBugatti1) {
        this.QueueTitleBugatti1 = QueueTitleBugatti1;
    }

    public JLabel getQueueTitleBugatti2() {
        return QueueTitleBugatti2;
    }

    public void setQueueTitleBugatti2(JLabel QueueTitleBugatti2) {
        this.QueueTitleBugatti2 = QueueTitleBugatti2;
    }

    public JLabel getQueueTitleBugatti3() {
        return QueueTitleBugatti3;
    }

    public void setQueueTitleBugatti3(JLabel QueueTitleBugatti3) {
        this.QueueTitleBugatti3 = QueueTitleBugatti3;
    }

    public JLabel getQueueTitleBugatti4() {
        return QueueTitleBugatti4;
    }

    public void setQueueTitleBugatti4(JLabel QueueTitleBugatti4) {
        this.QueueTitleBugatti4 = QueueTitleBugatti4;
    }

    public JLabel getQueueTitleLamborghini1() {
        return QueueTitleLamborghini1;
    }

    public void setQueueTitleLamborghini1(JLabel QueueTitleLamborghini1) {
        this.QueueTitleLamborghini1 = QueueTitleLamborghini1;
    }

    public JLabel getQueueTitleLamborghini2() {
        return QueueTitleLamborghini2;
    }

    public void setQueueTitleLamborghini2(JLabel QueueTitleLamborghini2) {
        this.QueueTitleLamborghini2 = QueueTitleLamborghini2;
    }

    public JLabel getQueueTitleLamborghini3() {
        return QueueTitleLamborghini3;
    }

    public void setQueueTitleLamborghini3(JLabel QueueTitleLamborghini3) {
        this.QueueTitleLamborghini3 = QueueTitleLamborghini3;
    }

    public JLabel getQueueTitleLamborghini4() {
        return QueueTitleLamborghini4;
    }

    public void setQueueTitleLamborghini4(JLabel QueueTitleLamborghini4) {
        this.QueueTitleLamborghini4 = QueueTitleLamborghini4;
    }

    public JLabel getRacingIDBugatti() {
        return RacingIDBugatti;
    }

    public void setRacingIDBugatti(JLabel RacingIDBugatti) {
        this.RacingIDBugatti = RacingIDBugatti;
    }

    public JLabel getRacingIDLamborghini() {
        return RacingIDLamborghini;
    }

    public void setRacingIDLamborghini(JLabel RacingIDLamborghini) {
        this.RacingIDLamborghini = RacingIDLamborghini;
    }

    public JLabel getRacingIDTitleBugatti() {
        return RacingIDTitleBugatti;
    }

    public void setRacingIDTitleBugatti(JLabel RacingIDTitleBugatti) {
        this.RacingIDTitleBugatti = RacingIDTitleBugatti;
    }

    public JLabel getRacingIDTitleLamborghini() {
        return RacingIDTitleLamborghini;
    }

    public void setRacingIDTitleLamborghini(JLabel RacingIDTitleLamborghini) {
        this.RacingIDTitleLamborghini = RacingIDTitleLamborghini;
    }

    public JLabel getRacingTimeBugatti() {
        return RacingTimeBugatti;
    }

    public void setRacingTimeBugatti(JLabel RacingTimeBugatti) {
        this.RacingTimeBugatti = RacingTimeBugatti;
    }

    public JLabel getRacingTimeLamborghini() {
        return RacingTimeLamborghini;
    }

    public void setRacingTimeLamborghini(JLabel RacingTimeLamborghini) {
        this.RacingTimeLamborghini = RacingTimeLamborghini;
    }

    public JLabel getRacingTimeTitleBugatti() {
        return RacingTimeTitleBugatti;
    }

    public void setRacingTimeTitleBugatti(JLabel RacingTimeTitleBugatti) {
        this.RacingTimeTitleBugatti = RacingTimeTitleBugatti;
    }

    public JLabel getRacingTimeTitleLamborghini() {
        return RacingTimeTitleLamborghini;
    }

    public void setRacingTimeTitleLamborghini(JLabel RacingTimeTitleLamborghini) {
        this.RacingTimeTitleLamborghini = RacingTimeTitleLamborghini;
    }

    public JLabel getRacingTitleBugatti() {
        return RacingTitleBugatti;
    }

    public void setRacingTitleBugatti(JLabel RacingTitleBugatti) {
        this.RacingTitleBugatti = RacingTitleBugatti;
    }

    public JLabel getRacingTitleLamborghini() {
        return RacingTitleLamborghini;
    }

    public void setRacingTitleLamborghini(JLabel RacingTitleLamborghini) {
        this.RacingTitleLamborghini = RacingTitleLamborghini;
    }

    public JLabel getResult() {
        return Result;
    }

    public void setResult(JLabel Result) {
        this.Result = Result;
    }

    public JLabel getResultTitle() {
        return ResultTitle;
    }

    public void setResultTitle(JLabel ResultTitle) {
        this.ResultTitle = ResultTitle;
    }

    public JPanel getResultWindow() {
        return ResultWindow;
    }

    public void setResultWindow(JPanel ResultWindow) {
        this.ResultWindow = ResultWindow;
    }

    public JPanel getResultWindowBugatti() {
        return ResultWindowBugatti;
    }

    public void setResultWindowBugatti(JPanel ResultWindowBugatti) {
        this.ResultWindowBugatti = ResultWindowBugatti;
    }

    public JPanel getResultWindowLamborghini() {
        return ResultWindowLamborghini;
    }

    public void setResultWindowLamborghini(JPanel ResultWindowLamborghini) {
        this.ResultWindowLamborghini = ResultWindowLamborghini;
    }

    public JButton getStopButton() {
        return StopButton;
    }

    public void setStopButton(JButton StopButton) {
        this.StopButton = StopButton;
    }

    public JPanel getTitleWindow() {
        return TitleWindow;
    }

    public void setTitleWindow(JPanel TitleWindow) {
        this.TitleWindow = TitleWindow;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JLabel getTitleBugatti() {
        return titleBugatti;
    }

    public void setTitleBugatti(JLabel titleBugatti) {
        this.titleBugatti = titleBugatti;
    }

    public JLabel getTitleLamborghini() {
        return titleLamborghini;
    }

    public void setTitleLamborghini(JLabel titleLamborghini) {
        this.titleLamborghini = titleLamborghini;
    }

    public JLabel getWinsBugatti() {
        return winsBugatti;
    }

    public void setWinsBugatti(JLabel winsBugatti) {
        this.winsBugatti = winsBugatti;
    }

    public JLabel getWinsLamborghini() {
        return winsLamborghini;
    }

    public void setWinsLamborghini(JLabel winsLamborghini) {
        this.winsLamborghini = winsLamborghini;
    }

    public JLabel getWinsTitleBugatti() {
        return winsTitleBugatti;
    }

    public void setWinsTitleBugatti(JLabel winsTitleBugatti) {
        this.winsTitleBugatti = winsTitleBugatti;
    }

    public JLabel getWinsTitleLamborghini() {
        return winsTitleLamborghini;
    }

    public void setWinsTitleLamborghini(JLabel winsTitleLamborghini) {
        this.winsTitleLamborghini = winsTitleLamborghini;
    }

    public JLabel getQtyRounds() {
        return qtyRounds;
    }

    public void setQtyRounds(JLabel qtyRounds) {
        this.qtyRounds = qtyRounds;
    }
    
    private void StopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StopButtonActionPerformed

    private void AITimeDecreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AITimeDecreaseActionPerformed
        if (Integer.parseInt(this.AITime.getText()) > 1) {
            int result = Integer.parseInt(this.AITime.getText());
            result--;
            String resultText = String.valueOf(result);
            this.AITime.setText(resultText);
        }
    }//GEN-LAST:event_AITimeDecreaseActionPerformed

    private void AITimeIncreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AITimeIncreaseActionPerformed
        int result = Integer.parseInt(this.AITime.getText());
        result++;
        String resultText = String.valueOf(result);
        this.AITime.setText(resultText);
    }//GEN-LAST:event_AITimeIncreaseActionPerformed

    private void QueueBugatti2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueueBugatti2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QueueBugatti2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AIStatus;
    private javax.swing.JLabel AITime;
    private javax.swing.JButton AITimeDecrease;
    private javax.swing.JButton AITimeIncrease;
    private javax.swing.JLabel AITimeTitle;
    private javax.swing.JLabel AITitle;
    private javax.swing.JPanel AIWindow;
    private javax.swing.JPanel BugattiWindow;
    private javax.swing.JPanel LamborghiniWindow;
    private javax.swing.JTextField QueueBugatti1;
    private javax.swing.JTextField QueueBugatti2;
    private javax.swing.JTextField QueueBugatti3;
    private javax.swing.JTextField QueueBugatti4;
    private javax.swing.JTextField QueueLamborghini1;
    private javax.swing.JTextField QueueLamborghini2;
    private javax.swing.JTextField QueueLamborghini3;
    private javax.swing.JTextField QueueLamborghini4;
    private javax.swing.JLabel QueueTitleBugatti1;
    private javax.swing.JLabel QueueTitleBugatti2;
    private javax.swing.JLabel QueueTitleBugatti3;
    private javax.swing.JLabel QueueTitleBugatti4;
    private javax.swing.JLabel QueueTitleLamborghini1;
    private javax.swing.JLabel QueueTitleLamborghini2;
    private javax.swing.JLabel QueueTitleLamborghini3;
    private javax.swing.JLabel QueueTitleLamborghini4;
    private javax.swing.JLabel RacingIDBugatti;
    private javax.swing.JLabel RacingIDLamborghini;
    private javax.swing.JLabel RacingIDTitleBugatti;
    private javax.swing.JLabel RacingIDTitleLamborghini;
    private javax.swing.JLabel RacingTimeBugatti;
    private javax.swing.JLabel RacingTimeLamborghini;
    private javax.swing.JLabel RacingTimeTitleBugatti;
    private javax.swing.JLabel RacingTimeTitleLamborghini;
    private javax.swing.JLabel RacingTitleBugatti;
    private javax.swing.JLabel RacingTitleLamborghini;
    private javax.swing.JLabel Result;
    private javax.swing.JLabel ResultTitle;
    private javax.swing.JPanel ResultWindow;
    private javax.swing.JPanel ResultWindowBugatti;
    private javax.swing.JPanel ResultWindowLamborghini;
    private javax.swing.JButton StopButton;
    private javax.swing.JPanel TitleWindow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel qtyRounds;
    private javax.swing.JLabel roundsTitle;
    private javax.swing.JLabel titleBugatti;
    private javax.swing.JLabel titleLamborghini;
    private javax.swing.JLabel winsBugatti;
    private javax.swing.JLabel winsLamborghini;
    private javax.swing.JLabel winsTitleBugatti;
    private javax.swing.JLabel winsTitleLamborghini;
    // End of variables declaration//GEN-END:variables
}
